//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalHealthRecord.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonalHealthRecord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ann Arbor
        ///Baton Rouge
        ///Broken Arrow
        ///Cape Coral
        ///Cedar Rapids
        ///Charleston
        ///Chula Vista
        ///College Station
        ///Colorado Springs
        ///Columbia
        ///Coral Springs
        ///Corpus Christi
        ///Costa Mesa
        ///Daly City
        ///Des Moines
        ///El Cajon
        ///Elizabeth
        ///Elk Grove
        ///El Monte
        ///El Paso
        ///Fargo
        ///Fort Collins
        ///Fort Lauderdale
        ///Fort Wayne
        ///Fort Worth
        ///Garden Grove
        ///Grand Prairie
        ///Grand Rapids
        ///Green Bay
        ///High Point
        ///Huntington Beach
        ///Jersey City
        ///Jurupa Valley
        ///Kansas City
        ///Las Cruces
        ///Las Vegas
        ///League City
        ///Little Rock
        ///Long Beach
        ///Los Angeles
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abel
        ///Abraham
        ///Absolon
        ///Ada
        ///Adalbert
        ///Adalberta
        ///Adam
        ///Adela
        ///Adelaida
        ///Adelard
        ///Adelina
        ///Adina
        ///Adolf
        ///Adolfina
        ///Adrian
        ///Adriana
        ///Adriena
        ///Afra
        ///Afrodita
        ///Agap
        ///Agapa
        ///Agapia
        ///Agata
        ///Agaton
        ///Aglaja
        ///Agnesa
        ///Agnesa
        ///Achac
        ///Achiles
        ///Aida
        ///Aladar
        ///Alan
        ///Alana
        ///Albert
        ///Alberta
        ///Albertin
        ///Albertina
        ///Albin
        ///Albina
        ///Albrecht
        ///Albrechta
        ///Alena
        ///Ales
        ///Alex
        ///Alexander
        ///Alexandra
        ///Alexej
        ///Alexia
        ///Alfonz
        ///Alfonzia
        ///Alfred
        ///Alfreda
        ///Algelina
        ///Alica
        ///Alida
        ///Alina
        ///Alma
        ///Alojz
        ///Alojzia
        ///Alzbeta
        ///Amadea
        ///Amadeus
        ///Amalia        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VZP
        ///Union
        ///Socialna poistovna
        ///Wustenrot
        ///Kooperativa
        ///Generali
        ///CSOB
        ///AXA
        ///Allianz
        ///AEGON
        ///ASTRA
        ///NOVIS
        ///Komunalna poistovna
        ///UNIQA
        ///MetLife
        ///.
        /// </summary>
        internal static string InsuranceAgencyCode {
            get {
                return ResourceManager.GetString("InsuranceAgencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Jones
        ///Taylor
        ///Williams
        ///Brown
        ///Davies
        ///Evans
        ///Wilson
        ///Thomas
        ///Roberts
        ///Johnson
        ///Lewis
        ///Walker
        ///Robinson
        ///Wood
        ///Thompson
        ///White
        ///Watson
        ///Jackson
        ///Wright
        ///Green
        ///Harris
        ///Cooper
        ///King
        ///Lee
        ///Martin
        ///Clarke
        ///James
        ///Morgan
        ///Hughes
        ///Edwards
        ///Hill
        ///Moore
        ///Clark
        ///Harrison
        ///Scott
        ///Young
        ///Morris
        ///Hall
        ///Ward
        ///Turner
        ///Carter
        ///Phillips
        ///Mitchell
        ///Patel
        ///Adams
        ///Campbell
        ///Anderson
        ///Allen
        ///Cook
        ///Bailey
        ///Parker
        ///Miller
        ///Davis
        ///Murphy
        ///Price
        ///Bell
        ///Baker
        ///Griffiths
        ///Kelly
        ///Simpson
        ///Marshall
        ///Collins
        ///Bennett
        ///Cox
        ///Ric [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
    }
}
