version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-orcl
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
  debug:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-orcl
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run watch
  shell:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-orcl
    env_file: .env
    volumes:
      - .:/usr/src/app
    command: bash
